// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kedge/config/http/routes/matcher.proto

package kedge_config_http_routes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Matcher) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
