sudo: false
language: go
go:
  - 1.8.x

install:
  # Get just particular release. Use curl https://glide.sh/get | sh when fixed (currently API request limits).
  - wget "https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.12.3-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"
  - glide install

script:
 - ./test_all.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)