sudo: false
language: go
go:
  - 1.8.x

install:
  - go get k8s.io/kubernetes/pkg/client/unversioned/clientcmd
  - go get -t ./...

script:
 - ./test_all.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)