required = ["github.com/mwitkow/go-proto-validators/protoc-gen-govalidators", "github.com/gogo/protobuf/protoc-gen-gogofast"]

[[constraint]]
  name = "github.com/mwitkow/grpc-proxy"
  revision = "67591eb23c48346a480470e462289835d96f70da"

[[constraint]]
  name = "github.com/Bplotka/oidc"
  version = "v0.5.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  revision = "39de4380c2e0353a115b80b1c730719c79bfb771"
