required = ["github.com/mwitkow/go-proto-validators/protoc-gen-govalidators", "github.com/gogo/protobuf/protoc-gen-gogofast"]

[[constraint]]
  name = "github.com/mwitkow/grpc-proxy"
  revision = "67591eb23c48346a480470e462289835d96f70da"

