requires = ["github.com/mwitkow/go-proto-validators/protoc-gen-govalidators", "github.com/gogo/protobuf/protoc-gen-gogofast"]

[[constraint]]
  name = "github.com/Bplotka/oidc"

[[constraint]]
  name = "github.com/fortytw2/leaktest"

[[constraint]]
  name = "github.com/go-chi/chi"

[[constraint]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/google/uuid"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  name = "github.com/improbable-eng/go-httpwares"

[[constraint]]
  name = "github.com/improbable-eng/go-srvlb"

[[constraint]]
  name = "github.com/jpillora/backoff"

[[constraint]]
  name = "github.com/mwitkow/go-conntrack"

[[constraint]]
  name = "github.com/mwitkow/go-flagz"

[[constraint]]
  name = "github.com/mwitkow/go-proto-validators"

[[constraint]]
  name = "github.com/mwitkow/grpc-proxy"
  revision = "67591eb23c48346a480470e462289835d96f70da"

[[constraint]]
  name = "github.com/oklog/oklog"

[[constraint]]
  name = "github.com/oxtoacart/bpool"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/pressly/chi"

[[constraint]]
  name = "github.com/prometheus/client_golang"

[[constraint]]
  name = "github.com/prometheus/client_model"

[[constraint]]
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/rs/cors"

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "google.golang.org/grpc"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
