// Code generated by protoc-gen-go.
// source: kedge/config/director.proto
// DO NOT EDIT!

package kedge_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import  kedge_config_grpc_routes "github.com/mwitkow/kedge/_protogen/kedge/config/grpc/routes"
import  kedge_config_http_routes "github.com/mwitkow/kedge/_protogen/kedge/config/http/routes"
import  kedge_config_http_routes1 "github.com/mwitkow/kedge/_protogen/kedge/config/http/routes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// / DirectorConfig is the top level configuration message the director.
type DirectorConfig struct {
	Grpc *DirectorConfig_Grpc `protobuf:"bytes,1,opt,name=grpc" json:"grpc,omitempty"`
	Http *DirectorConfig_Http `protobuf:"bytes,2,opt,name=http" json:"http,omitempty"`
}

func (m *DirectorConfig) Reset()                    { *m = DirectorConfig{} }
func (m *DirectorConfig) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig) ProtoMessage()               {}
func (*DirectorConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *DirectorConfig) GetGrpc() *DirectorConfig_Grpc {
	if m != nil {
		return m.Grpc
	}
	return nil
}

func (m *DirectorConfig) GetHttp() *DirectorConfig_Http {
	if m != nil {
		return m.Http
	}
	return nil
}

type DirectorConfig_Grpc struct {
	Routes []*kedge_config_grpc_routes.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *DirectorConfig_Grpc) Reset()                    { *m = DirectorConfig_Grpc{} }
func (m *DirectorConfig_Grpc) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig_Grpc) ProtoMessage()               {}
func (*DirectorConfig_Grpc) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *DirectorConfig_Grpc) GetRoutes() []*kedge_config_grpc_routes.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type DirectorConfig_Http struct {
	Routes     []*kedge_config_http_routes1.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
	AdhocRules []*kedge_config_http_routes.Adhoc  `protobuf:"bytes,2,rep,name=adhoc_rules,json=adhocRules" json:"adhoc_rules,omitempty"`
}

func (m *DirectorConfig_Http) Reset()                    { *m = DirectorConfig_Http{} }
func (m *DirectorConfig_Http) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig_Http) ProtoMessage()               {}
func (*DirectorConfig_Http) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 1} }

func (m *DirectorConfig_Http) GetRoutes() []*kedge_config_http_routes1.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *DirectorConfig_Http) GetAdhocRules() []*kedge_config_http_routes.Adhoc {
	if m != nil {
		return m.AdhocRules
	}
	return nil
}

func init() {
	proto.RegisterType((*DirectorConfig)(nil), "kedge.config.DirectorConfig")
	proto.RegisterType((*DirectorConfig_Grpc)(nil), "kedge.config.DirectorConfig.Grpc")
	proto.RegisterType((*DirectorConfig_Http)(nil), "kedge.config.DirectorConfig.Http")
}

func init() { proto.RegisterFile("kedge/config/director.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0xb1, 0x4a, 0xc0, 0x30,
	0x14, 0x45, 0x49, 0x2d, 0x1d, 0x5e, 0xc5, 0x21, 0x53, 0x88, 0x83, 0x55, 0x2c, 0x74, 0x4a, 0xa1,
	0x22, 0x8e, 0x2a, 0x0a, 0x3a, 0xe7, 0x07, 0x44, 0xd3, 0xd8, 0x16, 0xc5, 0x84, 0x34, 0xfd, 0x00,
	0xbf, 0xcd, 0x1f, 0x93, 0x97, 0x46, 0x68, 0x40, 0xa9, 0x53, 0x86, 0x9c, 0x7b, 0xee, 0xe5, 0xc1,
	0xf1, 0x9b, 0xee, 0x07, 0xdd, 0x2a, 0xf3, 0xf1, 0x3a, 0x0d, 0x6d, 0x3f, 0x39, 0xad, 0xbc, 0x71,
	0xc2, 0x3a, 0xe3, 0x0d, 0x3d, 0x0c, 0x9f, 0x62, 0xfd, 0xe4, 0x75, 0x82, 0x0e, 0xce, 0xaa, 0xd6,
	0x99, 0xc5, 0xeb, 0x39, 0x3e, 0x6b, 0x88, 0x9f, 0x27, 0xd8, 0xe8, 0xbd, 0xfd, 0xc1, 0x9e, 0xfb,
	0xd1, 0xa8, 0x48, 0xd5, 0x7f, 0x52, 0x5b, 0xd9, 0xd9, 0x57, 0x06, 0x47, 0xf7, 0x71, 0xd4, 0x5d,
	0x60, 0xe9, 0x25, 0xe4, 0xd8, 0xcd, 0x48, 0x45, 0x9a, 0xb2, 0x3b, 0x15, 0xdb, 0x8d, 0x22, 0x65,
	0xc5, 0x83, 0xb3, 0x4a, 0x06, 0x1c, 0x63, 0xd8, 0xc2, 0xb2, 0x7f, 0xc4, 0x1e, 0xbd, 0xb7, 0x32,
	0xe0, 0xfc, 0x1a, 0x72, 0x94, 0xd0, 0x2b, 0x28, 0xd6, 0x61, 0x8c, 0x54, 0x07, 0x4d, 0xd9, 0x9d,
	0xa4, 0x02, 0xac, 0x10, 0x71, 0xb9, 0xc4, 0x47, 0x46, 0x9c, 0x7f, 0x12, 0xc8, 0xd1, 0xb7, 0x67,
	0xc0, 0xb6, 0x5f, 0x0d, 0xf4, 0x06, 0xca, 0x70, 0xb9, 0x27, 0xb7, 0xbc, 0xeb, 0x99, 0x65, 0x7b,
	0xe9, 0x5b, 0x84, 0x25, 0x84, 0x8c, 0xc4, 0xc8, 0x4b, 0x11, 0x8e, 0x79, 0xf1, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xcd, 0x16, 0x20, 0x3b, 0xed, 0x01, 0x00, 0x00,
}
