// Code generated by protoc-gen-go.
// source: kedge/config/director.proto
// DO NOT EDIT!

package kedge_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import kedge_config_grpc_routes  "github.com/mwitkow/kedge/_protogen/kedge/config/grpc/routes"
import kedge_config_http_routes  "github.com/mwitkow/kedge/_protogen/kedge/config/http/routes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// / DirectorConfig is the top level configuration message the director.
type DirectorConfig struct {
	Grpc *DirectorConfig_Grpc `protobuf:"bytes,1,opt,name=grpc" json:"grpc,omitempty"`
	Http *DirectorConfig_Http `protobuf:"bytes,2,opt,name=http" json:"http,omitempty"`
}

func (m *DirectorConfig) Reset()                    { *m = DirectorConfig{} }
func (m *DirectorConfig) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig) ProtoMessage()               {}
func (*DirectorConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *DirectorConfig) GetGrpc() *DirectorConfig_Grpc {
	if m != nil {
		return m.Grpc
	}
	return nil
}

func (m *DirectorConfig) GetHttp() *DirectorConfig_Http {
	if m != nil {
		return m.Http
	}
	return nil
}

type DirectorConfig_Grpc struct {
	Routes []*kedge_config_grpc_routes.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *DirectorConfig_Grpc) Reset()                    { *m = DirectorConfig_Grpc{} }
func (m *DirectorConfig_Grpc) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig_Grpc) ProtoMessage()               {}
func (*DirectorConfig_Grpc) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *DirectorConfig_Grpc) GetRoutes() []*kedge_config_grpc_routes.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type DirectorConfig_Http struct {
	Routes []*kedge_config_http_routes.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *DirectorConfig_Http) Reset()                    { *m = DirectorConfig_Http{} }
func (m *DirectorConfig_Http) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig_Http) ProtoMessage()               {}
func (*DirectorConfig_Http) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 1} }

func (m *DirectorConfig_Http) GetRoutes() []*kedge_config_http_routes.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*DirectorConfig)(nil), "kedge.config.DirectorConfig")
	proto.RegisterType((*DirectorConfig_Grpc)(nil), "kedge.config.DirectorConfig.Grpc")
	proto.RegisterType((*DirectorConfig_Http)(nil), "kedge.config.DirectorConfig.Http")
}

func init() { proto.RegisterFile("kedge/config/director.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x4e, 0x4d, 0x49,
	0x4f, 0xd5, 0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x4f, 0xc9, 0x2c, 0x4a, 0x4d, 0x2e, 0xc9,
	0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0x4b, 0xea, 0x41, 0x24, 0xa5, 0x54,
	0x51, 0x94, 0xa6, 0x17, 0x15, 0x24, 0xeb, 0x17, 0xe5, 0x97, 0x96, 0xa4, 0x16, 0x43, 0x29, 0x88,
	0x26, 0x34, 0x65, 0x19, 0x25, 0x25, 0x05, 0xd8, 0x94, 0x29, 0x35, 0x30, 0x71, 0xf1, 0xb9, 0x40,
	0xad, 0x73, 0x06, 0xab, 0x15, 0x32, 0xe5, 0x62, 0x01, 0x99, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x6d, 0xa4, 0xa8, 0x87, 0x6c, 0xbb, 0x1e, 0xaa, 0x5a, 0x3d, 0xf7, 0xa2, 0x82, 0xe4, 0x20, 0xb0,
	0x72, 0x90, 0x36, 0x90, 0x2d, 0x12, 0x4c, 0x44, 0x68, 0xf3, 0x28, 0x29, 0x29, 0x08, 0x02, 0x2b,
	0x97, 0xb2, 0xe7, 0x62, 0x01, 0x19, 0x22, 0x64, 0xce, 0xc5, 0x06, 0x71, 0x98, 0x04, 0xa3, 0x02,
	0xb3, 0x06, 0xb7, 0x91, 0x3c, 0xaa, 0x01, 0x20, 0x2b, 0xf4, 0xa0, 0x2e, 0x0f, 0x02, 0x51, 0x41,
	0x50, 0xe5, 0x20, 0x03, 0x40, 0xc6, 0x11, 0x32, 0x00, 0x64, 0x19, 0x56, 0x03, 0x92, 0xd8, 0xc0,
	0x21, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x84, 0x61, 0x17, 0x84, 0x01, 0x00, 0x00,
}
