// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: e2e/hello.proto

/*
Package e2e_helloworld is a generated protocol buffer package.

It is generated from these files:
	e2e/hello.proto

It has these top-level messages:
	HelloRequest
	HelloReply
*/
package e2e_helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *HelloRequest) Validate() error {
	return nil
}
func (this *HelloReply) Validate() error {
	return nil
}
