// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kedge/config/common/adhoc.proto

/*
Package kedge_config_common is a generated protocol buffer package.

It is generated from these files:
	kedge/config/common/adhoc.proto

It has these top-level messages:
	Adhoc
*/
package kedge_config_common

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Adhoc) Validate() error {
	if nil == this.Port {
		return go_proto_validators.FieldError("Port", fmt.Errorf("message must exist"))
	}
	if this.Port != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Port); err != nil {
			return go_proto_validators.FieldError("Port", err)
		}
	}
	if this.DnsNameReplace != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.DnsNameReplace); err != nil {
			return go_proto_validators.FieldError("DnsNameReplace", err)
		}
	}
	return nil
}
func (this *Adhoc_Port) Validate() error {
	for _, item := range this.AllowedRanges {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("AllowedRanges", err)
			}
		}
	}
	return nil
}
func (this *Adhoc_Port_Range) Validate() error {
	return nil
}
func (this *Adhoc_Replace) Validate() error {
	return nil
}
