// Code generated by protoc-gen-go.
// source: kfe/config/backendpool.proto
// DO NOT EDIT!

/*
Package kfe_config is a generated protocol buffer package.

It is generated from these files:
	kfe/config/backendpool.proto
	kfe/config/director.proto

It has these top-level messages:
	BackendPoolConfig
	TlsServerConfig
	DirectorConfig
*/
package kfe_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import  kfe_config_grpc_backends "github.com/mwitkow/kfe/_protogen/kfe/config/grpc/backends"
import  kfe_config_http_backends "github.com/mwitkow/kfe/_protogen/kfe/config/http/backends"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Config is the top level configuration message for a backend pool.
type BackendPoolConfig struct {
	TlsServerConfigs []*TlsServerConfig      `protobuf:"bytes,1,rep,name=tls_server_configs,json=tlsServerConfigs" json:"tls_server_configs,omitempty"`
	Grpc             *BackendPoolConfig_Grpc `protobuf:"bytes,2,opt,name=grpc" json:"grpc,omitempty"`
	Http             *BackendPoolConfig_Grpc `protobuf:"bytes,3,opt,name=http" json:"http,omitempty"`
}

func (m *BackendPoolConfig) Reset()                    { *m = BackendPoolConfig{} }
func (m *BackendPoolConfig) String() string            { return proto.CompactTextString(m) }
func (*BackendPoolConfig) ProtoMessage()               {}
func (*BackendPoolConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BackendPoolConfig) GetTlsServerConfigs() []*TlsServerConfig {
	if m != nil {
		return m.TlsServerConfigs
	}
	return nil
}

func (m *BackendPoolConfig) GetGrpc() *BackendPoolConfig_Grpc {
	if m != nil {
		return m.Grpc
	}
	return nil
}

func (m *BackendPoolConfig) GetHttp() *BackendPoolConfig_Grpc {
	if m != nil {
		return m.Http
	}
	return nil
}

type BackendPoolConfig_Grpc struct {
	Backends []*kfe_config_grpc_backends.Backend `protobuf:"bytes,1,rep,name=backends" json:"backends,omitempty"`
}

func (m *BackendPoolConfig_Grpc) Reset()                    { *m = BackendPoolConfig_Grpc{} }
func (m *BackendPoolConfig_Grpc) String() string            { return proto.CompactTextString(m) }
func (*BackendPoolConfig_Grpc) ProtoMessage()               {}
func (*BackendPoolConfig_Grpc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *BackendPoolConfig_Grpc) GetBackends() []*kfe_config_grpc_backends.Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

type BackendPoolConfig_Http struct {
	Backends []*kfe_config_http_backends.Backend `protobuf:"bytes,1,rep,name=backends" json:"backends,omitempty"`
}

func (m *BackendPoolConfig_Http) Reset()                    { *m = BackendPoolConfig_Http{} }
func (m *BackendPoolConfig_Http) String() string            { return proto.CompactTextString(m) }
func (*BackendPoolConfig_Http) ProtoMessage()               {}
func (*BackendPoolConfig_Http) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *BackendPoolConfig_Http) GetBackends() []*kfe_config_http_backends.Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

type TlsServerConfig struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *TlsServerConfig) Reset()                    { *m = TlsServerConfig{} }
func (m *TlsServerConfig) String() string            { return proto.CompactTextString(m) }
func (*TlsServerConfig) ProtoMessage()               {}
func (*TlsServerConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TlsServerConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*BackendPoolConfig)(nil), "kfe.config.BackendPoolConfig")
	proto.RegisterType((*BackendPoolConfig_Grpc)(nil), "kfe.config.BackendPoolConfig.Grpc")
	proto.RegisterType((*BackendPoolConfig_Http)(nil), "kfe.config.BackendPoolConfig.Http")
	proto.RegisterType((*TlsServerConfig)(nil), "kfe.config.TlsServerConfig")
}

func init() { proto.RegisterFile("kfe/config/backendpool.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0x4e, 0x4b, 0xd5,
	0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x4f, 0x4a, 0x4c, 0xce, 0x4e, 0xcd, 0x4b, 0x29, 0xc8,
	0xcf, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0x4e, 0x4b, 0xd5, 0x83, 0xc8,
	0x4a, 0xa9, 0x21, 0xa9, 0x4c, 0x2f, 0x2a, 0x48, 0x86, 0x29, 0x2f, 0x86, 0x31, 0x20, 0x7a, 0x50,
	0xd4, 0x65, 0x94, 0x94, 0x14, 0xe0, 0x50, 0xa7, 0x74, 0x87, 0x89, 0x4b, 0xd0, 0x09, 0x22, 0x12,
	0x90, 0x9f, 0x9f, 0xe3, 0x0c, 0xd6, 0x21, 0xe4, 0xc9, 0x25, 0x54, 0x92, 0x53, 0x1c, 0x5f, 0x9c,
	0x5a, 0x54, 0x96, 0x5a, 0x14, 0x0f, 0x31, 0xa6, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48,
	0x5a, 0x0f, 0xe1, 0x1c, 0xbd, 0x90, 0x9c, 0xe2, 0x60, 0xb0, 0x22, 0x88, 0xc6, 0x20, 0x81, 0x12,
	0x54, 0x81, 0x62, 0x21, 0x33, 0x2e, 0x16, 0x90, 0x3b, 0x25, 0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d,
	0x94, 0x90, 0x35, 0x63, 0xd8, 0xab, 0xe7, 0x5e, 0x54, 0x90, 0x1c, 0x04, 0x56, 0x0f, 0xd2, 0x07,
	0x72, 0xb7, 0x04, 0x33, 0xf1, 0xfa, 0x40, 0xea, 0xa5, 0x5c, 0xb9, 0x58, 0x40, 0x3c, 0x21, 0x5b,
	0x2e, 0x0e, 0x98, 0x97, 0xa1, 0x0e, 0x57, 0x44, 0x36, 0x03, 0x64, 0x87, 0x1e, 0x4c, 0x01, 0xcc,
	0xc4, 0x20, 0xb8, 0x16, 0x90, 0x31, 0x1e, 0x25, 0x25, 0x05, 0x84, 0x8c, 0x01, 0x59, 0x89, 0xc7,
	0x18, 0x25, 0x55, 0x2e, 0x7e, 0xb4, 0x20, 0x12, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0x91, 0x61, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x61, 0x8a, 0xc9, 0x16, 0x08, 0x02, 0x00, 0x00,
}
