// Code generated by protoc-gen-go.
// source: kfe/config/director.proto
// DO NOT EDIT!

package kfe_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import  kfe_config_grpc_routes "github.com/mwitkow/kfe/_protogen/kfe/config/grpc/routes"
import  kfe_config_http_routes "github.com/mwitkow/kfe/_protogen/kfe/config/http/routes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// / DirectorConfig is the top level configuration message the director.
type DirectorConfig struct {
	Grpc *DirectorConfig_Grpc `protobuf:"bytes,1,opt,name=grpc" json:"grpc,omitempty"`
	Http *DirectorConfig_Http `protobuf:"bytes,2,opt,name=http" json:"http,omitempty"`
}

func (m *DirectorConfig) Reset()                    { *m = DirectorConfig{} }
func (m *DirectorConfig) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig) ProtoMessage()               {}
func (*DirectorConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *DirectorConfig) GetGrpc() *DirectorConfig_Grpc {
	if m != nil {
		return m.Grpc
	}
	return nil
}

func (m *DirectorConfig) GetHttp() *DirectorConfig_Http {
	if m != nil {
		return m.Http
	}
	return nil
}

type DirectorConfig_Grpc struct {
	Routes []*kfe_config_grpc_routes.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *DirectorConfig_Grpc) Reset()                    { *m = DirectorConfig_Grpc{} }
func (m *DirectorConfig_Grpc) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig_Grpc) ProtoMessage()               {}
func (*DirectorConfig_Grpc) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *DirectorConfig_Grpc) GetRoutes() []*kfe_config_grpc_routes.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type DirectorConfig_Http struct {
	Routes []*kfe_config_http_routes.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *DirectorConfig_Http) Reset()                    { *m = DirectorConfig_Http{} }
func (m *DirectorConfig_Http) String() string            { return proto.CompactTextString(m) }
func (*DirectorConfig_Http) ProtoMessage()               {}
func (*DirectorConfig_Http) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 1} }

func (m *DirectorConfig_Http) GetRoutes() []*kfe_config_http_routes.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*DirectorConfig)(nil), "kfe.config.DirectorConfig")
	proto.RegisterType((*DirectorConfig_Grpc)(nil), "kfe.config.DirectorConfig.Grpc")
	proto.RegisterType((*DirectorConfig_Http)(nil), "kfe.config.DirectorConfig.Http")
}

func init() { proto.RegisterFile("kfe/config/director.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0x4e, 0x4b, 0xd5,
	0x4f, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x4f, 0xc9, 0x2c, 0x4a, 0x4d, 0x2e, 0xc9, 0x2f, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0x4e, 0x4b, 0xd5, 0x83, 0x48, 0x49, 0x29, 0x23,
	0x29, 0x4b, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0xca, 0x2f, 0x2d, 0x49, 0x2d, 0x86, 0x52, 0x10, 0x0d,
	0x28, 0x8a, 0x32, 0x4a, 0x4a, 0x0a, 0xb0, 0x29, 0x52, 0xfa, 0xc1, 0xc8, 0xc5, 0xe7, 0x02, 0xb5,
	0xc8, 0x19, 0xac, 0x56, 0xc8, 0x98, 0x8b, 0x05, 0x64, 0xa6, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7,
	0x91, 0xbc, 0x1e, 0xc2, 0x5e, 0x3d, 0x54, 0x95, 0x7a, 0xee, 0x45, 0x05, 0xc9, 0x41, 0x60, 0xc5,
	0x20, 0x4d, 0x20, 0x3b, 0x24, 0x98, 0x08, 0x6a, 0xf2, 0x28, 0x29, 0x29, 0x08, 0x02, 0x2b, 0x96,
	0xb2, 0xe5, 0x62, 0x01, 0x19, 0x21, 0x64, 0xca, 0xc5, 0x06, 0x71, 0x94, 0x04, 0xa3, 0x02, 0xb3,
	0x06, 0xb7, 0x91, 0x2c, 0xb2, 0x76, 0x90, 0xf1, 0x7a, 0x50, 0x37, 0x07, 0x81, 0xa8, 0x20, 0xa8,
	0x62, 0x90, 0x76, 0x90, 0x61, 0xf8, 0xb5, 0x83, 0x2c, 0xc2, 0xaa, 0x3d, 0x89, 0x0d, 0x1c, 0x02,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0x71, 0x54, 0x96, 0x74, 0x01, 0x00, 0x00,
}
