// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kedge/config/common/resolvers/resolvers.proto

/*
Package kedge_config_common_resolvers is a generated protocol buffer package.

It is generated from these files:
	kedge/config/common/resolvers/resolvers.proto

It has these top-level messages:
	SrvResolver
	K8SResolver
*/
package kedge_config_common_resolvers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / SrvBackend describes a backend that is resolved and load balanced using SRV.
type SrvResolver struct {
	// / dns_name specifies the address to look up using DNS SRV. Needs to be a FQDN.
	// / E.g. "_grpc._tcp.someservice.somenamespace.svc.cluster.local"
	DnsName string `protobuf:"bytes,1,opt,name=dns_name,json=dnsName" json:"dns_name,omitempty"`
	// / not recommended, but port override allows to ignore port form SRV record and use one defined here.
	// / Useful when there are multiple services identifed under the same domain.
	PortOverride uint32 `protobuf:"varint,2,opt,name=port_override,json=portOverride" json:"port_override,omitempty"`
}

func (m *SrvResolver) Reset()                    { *m = SrvResolver{} }
func (m *SrvResolver) String() string            { return proto.CompactTextString(m) }
func (*SrvResolver) ProtoMessage()               {}
func (*SrvResolver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SrvResolver) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

func (m *SrvResolver) GetPortOverride() uint32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

// / K8sResolver uses the Kubernetes Endpoints API to identify the service.
// / It watched Endpoint API for changes using the pod's credentails to fetch the service information.
type K8SResolver struct {
	// Common kube DNS name with optional port: "<service><|.namespace>(.whatever suffix)<|:port_name|:value number>"
	// to resolve by this resolver using endpoints API.
	// e.g ":backend1.namespace1:http_port1"
	DnsPortName string `protobuf:"bytes,1,opt,name=dns_port_name,json=dnsPortName" json:"dns_port_name,omitempty"`
}

func (m *K8SResolver) Reset()                    { *m = K8SResolver{} }
func (m *K8SResolver) String() string            { return proto.CompactTextString(m) }
func (*K8SResolver) ProtoMessage()               {}
func (*K8SResolver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *K8SResolver) GetDnsPortName() string {
	if m != nil {
		return m.DnsPortName
	}
	return ""
}

func init() {
	proto.RegisterType((*SrvResolver)(nil), "kedge.config.common.resolvers.SrvResolver")
	proto.RegisterType((*K8SResolver)(nil), "kedge.config.common.resolvers.K8sResolver")
}

func init() { proto.RegisterFile("kedge/config/common/resolvers/resolvers.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xcb, 0x0a, 0x82, 0x50,
	0x10, 0x40, 0xb1, 0x45, 0x8f, 0x6b, 0x6e, 0x5c, 0xd9, 0x22, 0x10, 0xdb, 0xb8, 0xe9, 0x4a, 0xb4,
	0xe9, 0x1f, 0xa2, 0x07, 0xf6, 0x01, 0x62, 0xde, 0x49, 0xa4, 0xee, 0x8c, 0xcc, 0x88, 0xdf, 0x1f,
	0x3e, 0xb0, 0x76, 0x33, 0x87, 0x33, 0x87, 0x51, 0xfb, 0x37, 0x98, 0x12, 0x92, 0x82, 0xf0, 0x55,
	0x95, 0x49, 0x41, 0xd6, 0x12, 0x26, 0x0c, 0x42, 0x9f, 0x16, 0x58, 0x7e, 0x93, 0xae, 0x99, 0x1a,
	0xf2, 0xb7, 0xbd, 0xae, 0x07, 0x5d, 0x0f, 0xba, 0x9e, 0xa4, 0xe8, 0xa2, 0xdc, 0x07, 0xb7, 0xe9,
	0xb8, 0xfb, 0x1b, 0xb5, 0x34, 0x28, 0x19, 0xe6, 0x16, 0x02, 0x27, 0x74, 0xe2, 0x55, 0xba, 0x30,
	0x28, 0xd7, 0xdc, 0x82, 0xbf, 0x53, 0x5e, 0x4d, 0xdc, 0x64, 0xd4, 0x02, 0x73, 0x65, 0x20, 0x98,
	0x85, 0x4e, 0xec, 0xa5, 0xeb, 0x0e, 0xde, 0x46, 0x16, 0x1d, 0x94, 0x7b, 0x3e, 0xc9, 0x94, 0x8b,
	0x94, 0xd7, 0xe5, 0xfa, 0xbb, 0xbf, 0xa6, 0x6b, 0x50, 0xee, 0xc4, 0x4d, 0xd7, 0x7d, 0xce, 0xfb,
	0x3f, 0x8f, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0x8a, 0x4e, 0x97, 0xd8, 0x00, 0x00, 0x00,
}
