// Code generated by protoc-gen-gogo.
// source: kedge/config/common/resolvers/resolvers.proto
// DO NOT EDIT!

/*
Package kedge_config_common_resolvers is a generated protocol buffer package.

It is generated from these files:
	kedge/config/common/resolvers/resolvers.proto

It has these top-level messages:
	SrvResolver
	K8SResolver
	HostResolver
*/
package kedge_config_common_resolvers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SrvResolver) Validate() error {
	return nil
}
func (this *K8SResolver) Validate() error {
	return nil
}
func (this *HostResolver) Validate() error {
	return nil
}
