// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kedge/config/common/resolvers/resolvers.proto

/*
Package kedge_config_common_resolvers is a generated protocol buffer package.

It is generated from these files:
	kedge/config/common/resolvers/resolvers.proto

It has these top-level messages:
	SrvResolver
	KubeResolver
*/
package kedge_config_common_resolvers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / SrvBackend describes a backend that is resolved and load balanced using SRV.
type SrvResolver struct {
	// / dns_name specifies the address to look up using DNS SRV. Needs to be a FQDN.
	// / E.g. "_grpc._tcp.someservice.somenamespace.svc.cluster.local"
	DnsName string `protobuf:"bytes,1,opt,name=dns_name,json=dnsName" json:"dns_name,omitempty"`
	// / not recommended, but port override allows to ignore port form SRV record and use one defined here.
	// / Useful when there are multiple services identifed under the same domain.
	PortOverride uint32 `protobuf:"varint,2,opt,name=port_override,json=portOverride" json:"port_override,omitempty"`
}

func (m *SrvResolver) Reset()                    { *m = SrvResolver{} }
func (m *SrvResolver) String() string            { return proto.CompactTextString(m) }
func (*SrvResolver) ProtoMessage()               {}
func (*SrvResolver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SrvResolver) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

func (m *SrvResolver) GetPortOverride() uint32 {
	if m != nil {
		return m.PortOverride
	}
	return 0
}

// / KubeResolver uses the Kubernetes Endpoints API to identify the service.
// / It requires the job to run inside a K8S pod and uses the pod's credentails to fetch the service information.
type KubeResolver struct {
	// / namespace is the k8s namespace to use.
	// / If unset, it deafults to 'deafult'.
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	// / service_name is the k8s service name to use.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	// / port_name is the name of the port to bind in the service.
	PortName string `protobuf:"bytes,3,opt,name=port_name,json=portName" json:"port_name,omitempty"`
}

func (m *KubeResolver) Reset()                    { *m = KubeResolver{} }
func (m *KubeResolver) String() string            { return proto.CompactTextString(m) }
func (*KubeResolver) ProtoMessage()               {}
func (*KubeResolver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KubeResolver) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *KubeResolver) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *KubeResolver) GetPortName() string {
	if m != nil {
		return m.PortName
	}
	return ""
}

func init() {
	proto.RegisterType((*SrvResolver)(nil), "kedge.config.common.resolvers.SrvResolver")
	proto.RegisterType((*KubeResolver)(nil), "kedge.config.common.resolvers.KubeResolver")
}

func init() { proto.RegisterFile("kedge/config/common/resolvers/resolvers.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0xc3, 0x9a, 0xe8, 0x32, 0xcb, 0x5e, 0x7a, 0x5a, 0xa3, 0x26, 0x88, 0x17, 0x2e, 0x96,
	0x83, 0x8f, 0x61, 0xd4, 0x04, 0x1f, 0x80, 0x40, 0x3b, 0x12, 0x22, 0xed, 0x90, 0x29, 0xf6, 0xf9,
	0x4d, 0x0b, 0x0b, 0xb7, 0xf6, 0xfb, 0xbf, 0xfc, 0x7f, 0x06, 0x5e, 0x7f, 0x51, 0xf7, 0x58, 0x29,
	0xb2, 0x3f, 0x43, 0x5f, 0x29, 0x32, 0x86, 0x6c, 0xc5, 0xe8, 0x68, 0xf4, 0xc8, 0x6e, 0x7f, 0xc9,
	0x89, 0x69, 0x26, 0xf1, 0x14, 0x75, 0xb9, 0xe8, 0x72, 0xd1, 0xe5, 0x26, 0x15, 0x1f, 0x70, 0xfa,
	0x66, 0x5f, 0xaf, 0x7f, 0x71, 0x0f, 0x47, 0x6d, 0x5d, 0x63, 0x5b, 0x83, 0x97, 0x24, 0x4f, 0xca,
	0xb4, 0xbe, 0xd3, 0xd6, 0x7d, 0xb6, 0x06, 0xc5, 0x0b, 0x9c, 0x27, 0xe2, 0xb9, 0x21, 0x8f, 0xcc,
	0x83, 0xc6, 0xcb, 0x21, 0x4f, 0xca, 0x73, 0x9d, 0x05, 0xf8, 0xb5, 0xb2, 0x62, 0x84, 0xec, 0xfd,
	0xaf, 0xc3, 0xad, 0xef, 0x11, 0xd2, 0xd0, 0xe5, 0xa6, 0x56, 0x5d, 0x0b, 0x77, 0x20, 0x9e, 0x21,
	0x73, 0xc8, 0x7e, 0x50, 0xb8, 0x2c, 0x1e, 0xa2, 0x70, 0x5a, 0x59, 0x5c, 0x7d, 0x80, 0x34, 0xae,
	0xc6, 0xfc, 0x26, 0xe6, 0xc7, 0x00, 0x42, 0xd8, 0xdd, 0xc6, 0x13, 0xdf, 0xfe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x0b, 0x8f, 0xdd, 0x8f, 0x13, 0x01, 0x00, 0x00,
}
