// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base/serverstatus.proto

/*
Package base is a generated protocol buffer package.

It is generated from these files:
	base/serverstatus.proto

It has these top-level messages:
	HealthCheckResponse
	FlagzState
	VersionResponse
*/
package base

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *HealthCheckResponse) Validate() error {
	return nil
}
func (this *FlagzState) Validate() error {
	return nil
}
func (this *VersionResponse) Validate() error {
	return nil
}
