// Code generated by protoc-gen-go. DO NOT EDIT.
// source: winch/config/mapper.proto

package winch_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Protocol int32

const (
	Protocol_ANY  Protocol = 0
	Protocol_HTTP Protocol = 1
	Protocol_GRPC Protocol = 2
)

var Protocol_name = map[int32]string{
	0: "ANY",
	1: "HTTP",
	2: "GRPC",
}
var Protocol_value = map[string]int32{
	"ANY":  0,
	"HTTP": 1,
	"GRPC": 2,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}
func (Protocol) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// / MapperConfig is the top level configuration message for a winch mapper.
type MapperConfig struct {
	Routes []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *MapperConfig) Reset()                    { *m = MapperConfig{} }
func (m *MapperConfig) String() string            { return proto.CompactTextString(m) }
func (*MapperConfig) ProtoMessage()               {}
func (*MapperConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MapperConfig) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type Route struct {
	// Optional auth injection. Reference to AuthSource.
	BackendAuth string `protobuf:"bytes,1,opt,name=backend_auth,json=backendAuth" json:"backend_auth,omitempty"`
	ProxyAuth   string `protobuf:"bytes,2,opt,name=proxy_auth,json=proxyAuth" json:"proxy_auth,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Route_Direct
	//	*Route_Regexp
	Type     isRoute_Type `protobuf_oneof:"type"`
	Protocol Protocol     `protobuf:"varint,5,opt,name=protocol,enum=winch.config.Protocol" json:"protocol,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type isRoute_Type interface {
	isRoute_Type()
}

type Route_Direct struct {
	Direct *DirectRoute `protobuf:"bytes,3,opt,name=direct,oneof"`
}
type Route_Regexp struct {
	Regexp *RegexpRoute `protobuf:"bytes,4,opt,name=regexp,oneof"`
}

func (*Route_Direct) isRoute_Type() {}
func (*Route_Regexp) isRoute_Type() {}

func (m *Route) GetType() isRoute_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Route) GetBackendAuth() string {
	if m != nil {
		return m.BackendAuth
	}
	return ""
}

func (m *Route) GetProxyAuth() string {
	if m != nil {
		return m.ProxyAuth
	}
	return ""
}

func (m *Route) GetDirect() *DirectRoute {
	if x, ok := m.GetType().(*Route_Direct); ok {
		return x.Direct
	}
	return nil
}

func (m *Route) GetRegexp() *RegexpRoute {
	if x, ok := m.GetType().(*Route_Regexp); ok {
		return x.Regexp
	}
	return nil
}

func (m *Route) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_ANY
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Route) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Route_OneofMarshaler, _Route_OneofUnmarshaler, _Route_OneofSizer, []interface{}{
		(*Route_Direct)(nil),
		(*Route_Regexp)(nil),
	}
}

func _Route_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Route)
	// type
	switch x := m.Type.(type) {
	case *Route_Direct:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Direct); err != nil {
			return err
		}
	case *Route_Regexp:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Regexp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Route.Type has unexpected type %T", x)
	}
	return nil
}

func _Route_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Route)
	switch tag {
	case 3: // type.direct
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DirectRoute)
		err := b.DecodeMessage(msg)
		m.Type = &Route_Direct{msg}
		return true, err
	case 4: // type.regexp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RegexpRoute)
		err := b.DecodeMessage(msg)
		m.Type = &Route_Regexp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Route_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Route)
	// type
	switch x := m.Type.(type) {
	case *Route_Direct:
		s := proto.Size(x.Direct)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Route_Regexp:
		s := proto.Size(x.Regexp)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// / Simplest routing mechanism using just direct mapping between dns and (proxy) kedge target.
type DirectRoute struct {
	// Key needs to be in host:port format.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *DirectRoute) Reset()                    { *m = DirectRoute{} }
func (m *DirectRoute) String() string            { return proto.CompactTextString(m) }
func (*DirectRoute) ProtoMessage()               {}
func (*DirectRoute) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DirectRoute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DirectRoute) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type RegexpRoute struct {
	// Regexp RE2 expression that will be applied on given domain:port
	Exp string `protobuf:"bytes,1,opt,name=exp" json:"exp,omitempty"`
	// Kedge URL to be used if we have a match. It can be a string including variable from regexp expression in a form
	// of bash-like variable. E.g
	// exp = ([a-z0-9-].*)[.](?P<cluster>[a-z0-9-].*)[.]internal[.]example[.]org
	// in that case you can use following variable:
	// - ${cluster}
	Url string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *RegexpRoute) Reset()                    { *m = RegexpRoute{} }
func (m *RegexpRoute) String() string            { return proto.CompactTextString(m) }
func (*RegexpRoute) ProtoMessage()               {}
func (*RegexpRoute) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *RegexpRoute) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

func (m *RegexpRoute) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*MapperConfig)(nil), "winch.config.MapperConfig")
	proto.RegisterType((*Route)(nil), "winch.config.Route")
	proto.RegisterType((*DirectRoute)(nil), "winch.config.DirectRoute")
	proto.RegisterType((*RegexpRoute)(nil), "winch.config.RegexpRoute")
	proto.RegisterEnum("winch.config.Protocol", Protocol_name, Protocol_value)
}

func init() { proto.RegisterFile("winch/config/mapper.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x59, 0x0a, 0x15, 0xa6, 0xc4, 0x90, 0x35, 0x31, 0xc5, 0xc4, 0x58, 0xb9, 0xd8, 0x68,
	0x68, 0x93, 0x92, 0x78, 0xf1, 0x04, 0x98, 0xc8, 0x45, 0x43, 0x36, 0x5c, 0x3c, 0x99, 0x52, 0xd6,
	0xb6, 0xa1, 0xb0, 0xcd, 0xb2, 0x15, 0xf8, 0xb5, 0x26, 0xfe, 0x01, 0xff, 0x82, 0xd9, 0x6d, 0xc5,
	0x62, 0xf4, 0x36, 0x99, 0xef, 0xcd, 0x9b, 0xf7, 0xa0, 0xb3, 0x89, 0x57, 0x41, 0xe4, 0x06, 0x6c,
	0xf5, 0x1a, 0x87, 0xee, 0xd2, 0x4f, 0x53, 0xca, 0x9d, 0x94, 0x33, 0xc1, 0x70, 0x4b, 0x21, 0x27,
	0x47, 0x67, 0xb7, 0x61, 0x2c, 0xa2, 0x6c, 0xe6, 0x04, 0x6c, 0xe9, 0x2e, 0x37, 0xb1, 0x58, 0xb0,
	0x8d, 0x1b, 0xb2, 0x9e, 0x92, 0xf6, 0xde, 0xfc, 0x24, 0x9e, 0xfb, 0x82, 0xf1, 0xb5, 0xbb, 0x1f,
	0x73, 0x97, 0xee, 0x1d, 0xb4, 0x1e, 0x95, 0xeb, 0x48, 0xf9, 0xe0, 0x1b, 0xd0, 0x39, 0xcb, 0x04,
	0x5d, 0x9b, 0xc8, 0xd2, 0x6c, 0xc3, 0x3b, 0x71, 0xca, 0x6f, 0x1c, 0x22, 0x19, 0x29, 0x24, 0xdd,
	0x4f, 0x04, 0x75, 0xb5, 0xc1, 0x97, 0xd0, 0x9a, 0xf9, 0xc1, 0x82, 0xae, 0xe6, 0x2f, 0x7e, 0x26,
	0x22, 0x13, 0x59, 0xc8, 0x6e, 0x12, 0xa3, 0xd8, 0x0d, 0x32, 0x11, 0xe1, 0x73, 0x80, 0x94, 0xb3,
	0xed, 0x2e, 0x17, 0x54, 0x95, 0xa0, 0xa9, 0x36, 0x0a, 0xf7, 0x41, 0x9f, 0xc7, 0x9c, 0x06, 0xc2,
	0xd4, 0x2c, 0x64, 0x1b, 0x5e, 0xe7, 0xf0, 0xf1, 0xbd, 0x62, 0xea, 0xd9, 0xb8, 0x42, 0x0a, 0xa9,
	0x3c, 0xe2, 0x34, 0xa4, 0xdb, 0xd4, 0xac, 0xfd, 0x75, 0x44, 0x14, 0xdb, 0x1f, 0xe5, 0x52, 0xec,
	0x41, 0x43, 0x75, 0x0f, 0x58, 0x62, 0xd6, 0x2d, 0x64, 0x1f, 0x7b, 0xa7, 0x87, 0x67, 0x93, 0x82,
	0x92, 0xbd, 0x6e, 0xa8, 0x43, 0x4d, 0xec, 0x52, 0xda, 0x1d, 0x80, 0x51, 0x4a, 0x82, 0x4d, 0xd0,
	0x16, 0x74, 0x97, 0xb7, 0x1d, 0xea, 0x1f, 0xef, 0x17, 0x55, 0x0b, 0x11, 0xb9, 0x92, 0x24, 0xe3,
	0x49, 0x5e, 0xf3, 0x87, 0x64, 0x3c, 0x91, 0x16, 0xa5, 0x5c, 0x52, 0x28, 0xf3, 0xff, 0xb2, 0x90,
	0x39, 0xff, 0xb5, 0xb8, 0xbe, 0x82, 0xc6, 0x77, 0x46, 0x7c, 0x04, 0xda, 0xe0, 0xe9, 0xb9, 0x5d,
	0xc1, 0x0d, 0xa8, 0x8d, 0xa7, 0xd3, 0x49, 0x1b, 0xc9, 0xe9, 0x81, 0x4c, 0x46, 0xed, 0xea, 0x4c,
	0x57, 0x05, 0xfa, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xe4, 0x04, 0xdf, 0x47, 0x02, 0x00,
	0x00,
}
