// Code generated by protoc-gen-go.
// source: kedge/config/grpc/routes/routes.proto
// DO NOT EDIT!

/*
Package kedge_config_grpc_routes is a generated protocol buffer package.

It is generated from these files:
	kedge/config/grpc/routes/routes.proto

It has these top-level messages:
	Route
*/
package kedge_config_grpc_routes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Route is a mapping between invoked gRPC requests and backends that should serve it.
type Route struct {
	// / backend_name is the string identifying the backend to send data to.
	BackendName string `protobuf:"bytes,1,opt,name=backend_name,json=backendName" json:"backend_name,omitempty"`
	// / service_name_matcher is a globbing expression that matches a full gRPC service name.
	// / For example a method call to 'com.example.MyService/Create' would be matched by:
	// /  - com.example.MyService
	// /  - com.example.*
	// /  - com.*
	// /  - *
	// / If not present, '*' is default.
	ServiceNameMatcher string `protobuf:"bytes,2,opt,name=service_name_matcher,json=serviceNameMatcher" json:"service_name_matcher,omitempty"`
	// / authority_matcher matches on the ':authority' header (a.k.a. Host header) enabling Virtual Host-like proxying.
	// / The matching is done through lower-case string-equality.
	// / If none are present, the route skips ':authority' checks.
	AuthorityMatcher string `protobuf:"bytes,3,opt,name=authority_matcher,json=authorityMatcher" json:"authority_matcher,omitempty"`
	// / metadata_matcher matches any gRPC inbound request metadata.
	// / Each key provided must find a match for the route to match.
	// / The matching is done through lower-case key match and explicit string-equality of values.
	// / If a given metadata entry has more than one string value, at least one of them needs to match.
	// / If none are present, the route skips metadata checks.
	MetadataMatcher map[string]string `protobuf:"bytes,4,rep,name=metadata_matcher,json=metadataMatcher" json:"metadata_matcher,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Route) GetBackendName() string {
	if m != nil {
		return m.BackendName
	}
	return ""
}

func (m *Route) GetServiceNameMatcher() string {
	if m != nil {
		return m.ServiceNameMatcher
	}
	return ""
}

func (m *Route) GetAuthorityMatcher() string {
	if m != nil {
		return m.AuthorityMatcher
	}
	return ""
}

func (m *Route) GetMetadataMatcher() map[string]string {
	if m != nil {
		return m.MetadataMatcher
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "kedge.config.grpc.routes.Route")
}

func init() { proto.RegisterFile("kedge/config/grpc/routes/routes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0xd0, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x60, 0xda, 0xba, 0x82, 0xb3, 0x82, 0x35, 0xf4, 0x50, 0x3c, 0xad, 0x82, 0xb0, 0x20,
	0xa4, 0xa2, 0x1e, 0xc4, 0xa3, 0xe0, 0x71, 0x3d, 0xf4, 0x05, 0xca, 0x6c, 0x3a, 0x76, 0x4b, 0x4d,
	0xb3, 0x64, 0xa7, 0x0b, 0x7d, 0x29, 0x9f, 0x51, 0x9a, 0xc4, 0x82, 0xa0, 0xa7, 0x4c, 0xe6, 0xff,
	0x12, 0x32, 0x81, 0xdb, 0x8e, 0xea, 0x86, 0x0a, 0x65, 0xfa, 0x8f, 0xb6, 0x29, 0x1a, 0xbb, 0x57,
	0x85, 0x35, 0x03, 0xd3, 0x21, 0x2c, 0x72, 0x6f, 0x0d, 0x1b, 0x91, 0x3b, 0x26, 0x3d, 0x93, 0x13,
	0x93, 0x3e, 0xbf, 0xf9, 0x8a, 0x61, 0x51, 0x4e, 0xa5, 0xb8, 0x86, 0xf3, 0x2d, 0xaa, 0x8e, 0xfa,
	0xba, 0xea, 0x51, 0x53, 0x1e, 0xad, 0xa2, 0xf5, 0x59, 0xb9, 0x0c, 0xbd, 0x77, 0xd4, 0x24, 0xee,
	0x21, 0x3b, 0x90, 0x3d, 0xb6, 0x8a, 0x1c, 0xa9, 0x34, 0xb2, 0xda, 0x91, 0xcd, 0x63, 0x47, 0x45,
	0xc8, 0x26, 0xba, 0xf1, 0x89, 0xb8, 0x83, 0x4b, 0x1c, 0x78, 0x67, 0x6c, 0xcb, 0xe3, 0xcc, 0x13,
	0xc7, 0xd3, 0x39, 0xf8, 0xc1, 0x15, 0xa4, 0x9a, 0x18, 0x6b, 0x64, 0x9c, 0xed, 0xc9, 0x2a, 0x59,
	0x2f, 0x1f, 0x9e, 0xe4, 0x7f, 0x03, 0x48, 0xf7, 0x78, 0xb9, 0x09, 0xe7, 0xc2, 0x55, 0x6f, 0x3d,
	0xdb, 0xb1, 0xbc, 0xd0, 0xbf, 0xbb, 0x57, 0xaf, 0x90, 0xfd, 0x05, 0x45, 0x0a, 0x49, 0x47, 0x63,
	0x98, 0x78, 0x2a, 0x45, 0x06, 0x8b, 0x23, 0x7e, 0x0e, 0x14, 0x46, 0xf3, 0x9b, 0x97, 0xf8, 0x39,
	0xda, 0x9e, 0xba, 0x1f, 0x7d, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xa1, 0x67, 0x69, 0x7a,
	0x01, 0x00, 0x00,
}
