// Code generated by protoc-gen-go. DO NOT EDIT.
// source: winch/config/mapper.proto

package winch_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// / MapperConfig is the top level configuration message for a winch mapper.
type MapperConfig struct {
	Routes []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *MapperConfig) Reset()                    { *m = MapperConfig{} }
func (m *MapperConfig) String() string            { return proto.CompactTextString(m) }
func (*MapperConfig) ProtoMessage()               {}
func (*MapperConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MapperConfig) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type Route struct {
	// Optional auth injection. Reference to AuthSource.
	BackendAuth string `protobuf:"bytes,1,opt,name=backend_auth,json=backendAuth" json:"backend_auth,omitempty"`
	ProxyAuth   string `protobuf:"bytes,2,opt,name=proxy_auth,json=proxyAuth" json:"proxy_auth,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Route_Direct
	//	*Route_Regexp
	Type isRoute_Type `protobuf_oneof:"type"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type isRoute_Type interface {
	isRoute_Type()
}

type Route_Direct struct {
	Direct *DirectRoute `protobuf:"bytes,3,opt,name=direct,oneof"`
}
type Route_Regexp struct {
	Regexp *RegexpRoute `protobuf:"bytes,4,opt,name=regexp,oneof"`
}

func (*Route_Direct) isRoute_Type() {}
func (*Route_Regexp) isRoute_Type() {}

func (m *Route) GetType() isRoute_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Route) GetBackendAuth() string {
	if m != nil {
		return m.BackendAuth
	}
	return ""
}

func (m *Route) GetProxyAuth() string {
	if m != nil {
		return m.ProxyAuth
	}
	return ""
}

func (m *Route) GetDirect() *DirectRoute {
	if x, ok := m.GetType().(*Route_Direct); ok {
		return x.Direct
	}
	return nil
}

func (m *Route) GetRegexp() *RegexpRoute {
	if x, ok := m.GetType().(*Route_Regexp); ok {
		return x.Regexp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Route) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Route_OneofMarshaler, _Route_OneofUnmarshaler, _Route_OneofSizer, []interface{}{
		(*Route_Direct)(nil),
		(*Route_Regexp)(nil),
	}
}

func _Route_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Route)
	// type
	switch x := m.Type.(type) {
	case *Route_Direct:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Direct); err != nil {
			return err
		}
	case *Route_Regexp:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Regexp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Route.Type has unexpected type %T", x)
	}
	return nil
}

func _Route_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Route)
	switch tag {
	case 3: // type.direct
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DirectRoute)
		err := b.DecodeMessage(msg)
		m.Type = &Route_Direct{msg}
		return true, err
	case 4: // type.regexp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RegexpRoute)
		err := b.DecodeMessage(msg)
		m.Type = &Route_Regexp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Route_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Route)
	// type
	switch x := m.Type.(type) {
	case *Route_Direct:
		s := proto.Size(x.Direct)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Route_Regexp:
		s := proto.Size(x.Regexp)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// / Simplest routing mechanism using just direct mapping between dns and (proxy) kedge target.
type DirectRoute struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
}

func (m *DirectRoute) Reset()                    { *m = DirectRoute{} }
func (m *DirectRoute) String() string            { return proto.CompactTextString(m) }
func (*DirectRoute) ProtoMessage()               {}
func (*DirectRoute) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DirectRoute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DirectRoute) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type RegexpRoute struct {
	// Regexp expression that will be applied on given DNS.
	Exp string `protobuf:"bytes,1,opt,name=exp" json:"exp,omitempty"`
	// Kedge URL to be used if we have a match. It can be a string including two variables using
	// go template:
	// - {{ .Cluster }} if cluster_group_name is specified.
	Url string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	// If specified, target cluster name will be fetched from named regexp group.
	ClusterGroupName string `protobuf:"bytes,3,opt,name=cluster_group_name,json=clusterGroupName" json:"cluster_group_name,omitempty"`
}

func (m *RegexpRoute) Reset()                    { *m = RegexpRoute{} }
func (m *RegexpRoute) String() string            { return proto.CompactTextString(m) }
func (*RegexpRoute) ProtoMessage()               {}
func (*RegexpRoute) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *RegexpRoute) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

func (m *RegexpRoute) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RegexpRoute) GetClusterGroupName() string {
	if m != nil {
		return m.ClusterGroupName
	}
	return ""
}

func init() {
	proto.RegisterType((*MapperConfig)(nil), "winch.config.MapperConfig")
	proto.RegisterType((*Route)(nil), "winch.config.Route")
	proto.RegisterType((*DirectRoute)(nil), "winch.config.DirectRoute")
	proto.RegisterType((*RegexpRoute)(nil), "winch.config.RegexpRoute")
}

func init() { proto.RegisterFile("winch/config/mapper.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x6f, 0xda, 0xde, 0x40, 0x4f, 0xba, 0x90, 0x71, 0x93, 0x0a, 0x62, 0xcc, 0xaa, 0xa0,
	0x4d, 0xa0, 0x05, 0x37, 0xae, 0x5a, 0x05, 0xdd, 0xe8, 0x62, 0x5e, 0xa0, 0x4c, 0xd3, 0x31, 0x09,
	0x4d, 0x32, 0xc3, 0x74, 0xc6, 0xb6, 0xcf, 0xe6, 0xc3, 0x08, 0x3e, 0x89, 0xcc, 0x99, 0x50, 0xab,
	0xe8, 0x2e, 0x9c, 0xef, 0x3b, 0xff, 0x7f, 0xc8, 0xc0, 0x70, 0x5b, 0x36, 0x59, 0x91, 0x66, 0xa2,
	0x79, 0x29, 0xf3, 0xb4, 0x66, 0x52, 0x72, 0x95, 0x48, 0x25, 0xb4, 0x20, 0x03, 0x44, 0x89, 0x43,
	0x67, 0x37, 0x79, 0xa9, 0x0b, 0xb3, 0x4c, 0x32, 0x51, 0xa7, 0xf5, 0xb6, 0xd4, 0x6b, 0xb1, 0x4d,
	0x73, 0x31, 0x46, 0x75, 0xfc, 0xca, 0xaa, 0x72, 0xc5, 0xb4, 0x50, 0x9b, 0xf4, 0xf0, 0xe9, 0x52,
	0xe2, 0x5b, 0x18, 0x3c, 0x61, 0xea, 0x1d, 0xe6, 0x90, 0x2b, 0xf0, 0x95, 0x30, 0x9a, 0x6f, 0x42,
	0x2f, 0xea, 0x8e, 0x82, 0xc9, 0x69, 0x72, 0x5c, 0x93, 0x50, 0xcb, 0x68, 0xab, 0xc4, 0x6f, 0x1e,
	0xfc, 0xc7, 0x09, 0xb9, 0x84, 0xc1, 0x92, 0x65, 0x6b, 0xde, 0xac, 0x16, 0xcc, 0xe8, 0x22, 0xf4,
	0x22, 0x6f, 0xd4, 0xa7, 0x41, 0x3b, 0x9b, 0x19, 0x5d, 0x90, 0x73, 0x00, 0xa9, 0xc4, 0x6e, 0xef,
	0x84, 0x0e, 0x0a, 0x7d, 0x9c, 0x20, 0x9e, 0x82, 0xbf, 0x2a, 0x15, 0xcf, 0x74, 0xd8, 0x8d, 0xbc,
	0x51, 0x30, 0x19, 0x7e, 0x2f, 0xbe, 0x47, 0x86, 0x65, 0x8f, 0xff, 0x68, 0xab, 0xda, 0x25, 0xc5,
	0x73, 0xbe, 0x93, 0x61, 0xef, 0xb7, 0x25, 0x8a, 0xec, 0xb0, 0xe4, 0xd4, 0xb9, 0x0f, 0x3d, 0xbd,
	0x97, 0x3c, 0x9e, 0x41, 0x70, 0x94, 0x4a, 0x42, 0xe8, 0xae, 0xf9, 0xde, 0x5d, 0x3e, 0xf7, 0x3f,
	0xde, 0x2f, 0x3a, 0x91, 0x47, 0xed, 0xc8, 0x12, 0xa3, 0x2a, 0x77, 0xf2, 0x17, 0x31, 0xaa, 0x8a,
	0x05, 0x04, 0x47, 0x1d, 0x56, 0xb4, 0xb7, 0xfc, 0x88, 0xe0, 0x3b, 0xf9, 0x77, 0x04, 0xb9, 0x06,
	0x92, 0x55, 0x66, 0xa3, 0xb9, 0x5a, 0xe4, 0x4a, 0x18, 0xb9, 0x68, 0x58, 0xcd, 0xf1, 0x1f, 0xf4,
	0xe9, 0x49, 0x4b, 0x1e, 0x2c, 0x78, 0x66, 0x35, 0x5f, 0xfa, 0xf8, 0x6a, 0xd3, 0xcf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x67, 0xf9, 0xa7, 0x2d, 0x18, 0x02, 0x00, 0x00,
}
