// Code generated by protoc-gen-go.
// source: kfe/config/http/backends/backend.proto
// DO NOT EDIT!

/*
Package kfe_config_http_backends is a generated protocol buffer package.

It is generated from these files:
	kfe/config/http/backends/backend.proto

It has these top-level messages:
	Backend
	Middleware
	Security
*/
package kfe_config_http_backends

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import  kfe_config_common_resolvers "github.com/mwitkow/kfe/_protogen/kfe/config/common/resolvers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Balancer chooses which HTTP backend balancing policy to use.
type Balancer int32

const (
	// ROUND_ROBIN is the simpliest and default load balancing policy
	Balancer_ROUND_ROBIN Balancer = 0
)

var Balancer_name = map[int32]string{
	0: "ROUND_ROBIN",
}
var Balancer_value = map[string]int32{
	"ROUND_ROBIN": 0,
}

func (x Balancer) String() string {
	return proto.EnumName(Balancer_name, int32(x))
}
func (Balancer) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// / Backend is a pool of HTTP endpoints that are kept open
type Backend struct {
	// / name is the string identifying the bakcend in all other conifgs.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// / balancer decides which balancing policy to use.
	Balancer Balancer `protobuf:"varint,2,opt,name=balancer,enum=kfe.config.http.backends.Balancer" json:"balancer,omitempty"`
	// / disable_conntracking turns off the /debug/events tracing and Prometheus monitoring of the pool sie for this backend.
	DisableConntracking bool `protobuf:"varint,3,opt,name=disable_conntracking,json=disableConntracking" json:"disable_conntracking,omitempty"`
	// / security controls the TLS connection details for the backend (HTTPS). If not present, insecure HTTTP mode is used.
	Security *Security `protobuf:"bytes,4,opt,name=security" json:"security,omitempty"`
	// / interceptors controls what middleware will be available on every call made to this backend.
	// / These will be executed in order from left to right.
	Middlewares []*Middleware `protobuf:"bytes,5,rep,name=middlewares" json:"middlewares,omitempty"`
	// Types that are valid to be assigned to Resolver:
	//	*Backend_Srv
	//	*Backend_K8S
	Resolver isBackend_Resolver `protobuf_oneof:"resolver"`
}

func (m *Backend) Reset()                    { *m = Backend{} }
func (m *Backend) String() string            { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()               {}
func (*Backend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isBackend_Resolver interface {
	isBackend_Resolver()
}

type Backend_Srv struct {
	Srv *kfe_config_common_resolvers.SrvResolver `protobuf:"bytes,10,opt,name=srv,oneof"`
}
type Backend_K8S struct {
	K8S *kfe_config_common_resolvers.KubeResolver `protobuf:"bytes,11,opt,name=k8s,oneof"`
}

func (*Backend_Srv) isBackend_Resolver() {}
func (*Backend_K8S) isBackend_Resolver() {}

func (m *Backend) GetResolver() isBackend_Resolver {
	if m != nil {
		return m.Resolver
	}
	return nil
}

func (m *Backend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Backend) GetBalancer() Balancer {
	if m != nil {
		return m.Balancer
	}
	return Balancer_ROUND_ROBIN
}

func (m *Backend) GetDisableConntracking() bool {
	if m != nil {
		return m.DisableConntracking
	}
	return false
}

func (m *Backend) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *Backend) GetMiddlewares() []*Middleware {
	if m != nil {
		return m.Middlewares
	}
	return nil
}

func (m *Backend) GetSrv() *kfe_config_common_resolvers.SrvResolver {
	if x, ok := m.GetResolver().(*Backend_Srv); ok {
		return x.Srv
	}
	return nil
}

func (m *Backend) GetK8S() *kfe_config_common_resolvers.KubeResolver {
	if x, ok := m.GetResolver().(*Backend_K8S); ok {
		return x.K8S
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Backend) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Backend_OneofMarshaler, _Backend_OneofUnmarshaler, _Backend_OneofSizer, []interface{}{
		(*Backend_Srv)(nil),
		(*Backend_K8S)(nil),
	}
}

func _Backend_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Backend)
	// resolver
	switch x := m.Resolver.(type) {
	case *Backend_Srv:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Srv); err != nil {
			return err
		}
	case *Backend_K8S:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.K8S); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Backend.Resolver has unexpected type %T", x)
	}
	return nil
}

func _Backend_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Backend)
	switch tag {
	case 10: // resolver.srv
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kfe_config_common_resolvers.SrvResolver)
		err := b.DecodeMessage(msg)
		m.Resolver = &Backend_Srv{msg}
		return true, err
	case 11: // resolver.k8s
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kfe_config_common_resolvers.KubeResolver)
		err := b.DecodeMessage(msg)
		m.Resolver = &Backend_K8S{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Backend_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Backend)
	// resolver
	switch x := m.Resolver.(type) {
	case *Backend_Srv:
		s := proto.Size(x.Srv)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Backend_K8S:
		s := proto.Size(x.K8S)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Middleware struct {
	// Types that are valid to be assigned to Middleware:
	//	*Middleware_Prometheus
	Middleware isMiddleware_Middleware `protobuf_oneof:"Middleware"`
}

func (m *Middleware) Reset()                    { *m = Middleware{} }
func (m *Middleware) String() string            { return proto.CompactTextString(m) }
func (*Middleware) ProtoMessage()               {}
func (*Middleware) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isMiddleware_Middleware interface {
	isMiddleware_Middleware()
}

type Middleware_Prometheus struct {
	Prometheus *Middleware_Retry `protobuf:"bytes,1,opt,name=prometheus,oneof"`
}

func (*Middleware_Prometheus) isMiddleware_Middleware() {}

func (m *Middleware) GetMiddleware() isMiddleware_Middleware {
	if m != nil {
		return m.Middleware
	}
	return nil
}

func (m *Middleware) GetPrometheus() *Middleware_Retry {
	if x, ok := m.GetMiddleware().(*Middleware_Prometheus); ok {
		return x.Prometheus
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Middleware) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Middleware_OneofMarshaler, _Middleware_OneofUnmarshaler, _Middleware_OneofSizer, []interface{}{
		(*Middleware_Prometheus)(nil),
	}
}

func _Middleware_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Middleware)
	// Middleware
	switch x := m.Middleware.(type) {
	case *Middleware_Prometheus:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Prometheus); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Middleware.Middleware has unexpected type %T", x)
	}
	return nil
}

func _Middleware_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Middleware)
	switch tag {
	case 1: // Middleware.prometheus
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Middleware_Retry)
		err := b.DecodeMessage(msg)
		m.Middleware = &Middleware_Prometheus{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Middleware_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Middleware)
	// Middleware
	switch x := m.Middleware.(type) {
	case *Middleware_Prometheus:
		s := proto.Size(x.Prometheus)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Middleware_Retry struct {
	// / retry_count specifies how many times to retry.
	RetryCount uint32 `protobuf:"varint,1,opt,name=retry_count,json=retryCount" json:"retry_count,omitempty"`
	// / on_codes specifies the list of codes to retry on.
	OnCodes []uint32 `protobuf:"varint,2,rep,packed,name=on_codes,json=onCodes" json:"on_codes,omitempty"`
}

func (m *Middleware_Retry) Reset()                    { *m = Middleware_Retry{} }
func (m *Middleware_Retry) String() string            { return proto.CompactTextString(m) }
func (*Middleware_Retry) ProtoMessage()               {}
func (*Middleware_Retry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Middleware_Retry) GetRetryCount() uint32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func (m *Middleware_Retry) GetOnCodes() []uint32 {
	if m != nil {
		return m.OnCodes
	}
	return nil
}

// / Security settings for a backend.
type Security struct {
	// / insecure_skip_verify skips the server certificate verification completely.
	// / No TLS config (for testclient or server) will be used. This should *not* be used in production software.
	InsecureSkipVerify bool `protobuf:"varint,1,opt,name=insecure_skip_verify,json=insecureSkipVerify" json:"insecure_skip_verify,omitempty"`
	// / config_name indicates the TlsServerConfig to be used for this connection.
	ConfigName string `protobuf:"bytes,2,opt,name=config_name,json=configName" json:"config_name,omitempty"`
}

func (m *Security) Reset()                    { *m = Security{} }
func (m *Security) String() string            { return proto.CompactTextString(m) }
func (*Security) ProtoMessage()               {}
func (*Security) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Security) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func (m *Security) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func init() {
	proto.RegisterType((*Backend)(nil), "kfe.config.http.backends.Backend")
	proto.RegisterType((*Middleware)(nil), "kfe.config.http.backends.Middleware")
	proto.RegisterType((*Middleware_Retry)(nil), "kfe.config.http.backends.Middleware.Retry")
	proto.RegisterType((*Security)(nil), "kfe.config.http.backends.Security")
	proto.RegisterEnum("kfe.config.http.backends.Balancer", Balancer_name, Balancer_value)
}

func init() { proto.RegisterFile("kfe/config/http/backends/backend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x9b, 0x66, 0x97, 0x0d, 0x13, 0x16, 0x90, 0xd9, 0x83, 0x59, 0x0e, 0x44, 0x15, 0x42,
	0x61, 0x91, 0x52, 0x28, 0x97, 0x3d, 0x00, 0x87, 0x14, 0xa1, 0x45, 0x40, 0x57, 0x72, 0x05, 0x37,
	0x14, 0x25, 0xce, 0x74, 0xd7, 0x4a, 0x63, 0x47, 0x76, 0x5a, 0xd4, 0xc7, 0xe1, 0x01, 0x78, 0x47,
	0x14, 0xa7, 0x69, 0x73, 0xd9, 0x8a, 0xdb, 0x78, 0xe6, 0xff, 0x7e, 0x8f, 0x3d, 0x03, 0x2f, 0x8b,
	0x05, 0x8e, 0xb9, 0x92, 0x0b, 0x71, 0x33, 0xbe, 0xad, 0xeb, 0x6a, 0x9c, 0xa5, 0xbc, 0x40, 0x99,
	0x9b, 0x2e, 0x88, 0x2a, 0xad, 0x6a, 0x45, 0x68, 0xb1, 0xc0, 0xa8, 0xd5, 0x45, 0x8d, 0x2e, 0xea,
	0x74, 0xe7, 0xaf, 0x7b, 0x0e, 0x5c, 0x95, 0xa5, 0x92, 0x63, 0x8d, 0x46, 0x2d, 0xd7, 0xa8, 0xcd,
	0x3e, 0x6a, 0x6d, 0x46, 0x7f, 0x5c, 0x38, 0x89, 0x5b, 0x92, 0x10, 0x38, 0x92, 0x69, 0x89, 0xd4,
	0x09, 0x9c, 0xf0, 0x3e, 0xb3, 0x31, 0xf9, 0x08, 0x5e, 0x96, 0x2e, 0x53, 0xc9, 0x51, 0xd3, 0x61,
	0xe0, 0x84, 0x0f, 0x27, 0xa3, 0xe8, 0xae, 0x9b, 0xa3, 0x78, 0xab, 0x64, 0x3b, 0x86, 0xbc, 0x85,
	0xb3, 0x5c, 0x98, 0x34, 0x5b, 0x62, 0xc2, 0x95, 0x94, 0xb5, 0x4e, 0x79, 0x21, 0xe4, 0x0d, 0x75,
	0x03, 0x27, 0xf4, 0xd8, 0x93, 0x6d, 0x6d, 0xda, 0x2b, 0x35, 0x57, 0x1a, 0xe4, 0x2b, 0x2d, 0xea,
	0x0d, 0x3d, 0x0a, 0x9c, 0xd0, 0x3f, 0x74, 0xe5, 0x7c, 0xab, 0x64, 0x3b, 0x86, 0x7c, 0x06, 0xbf,
	0x14, 0x79, 0xbe, 0xc4, 0xdf, 0xa9, 0x46, 0x43, 0x8f, 0x03, 0x37, 0xf4, 0x27, 0x2f, 0xee, 0xb6,
	0xf8, 0xbe, 0x13, 0xb3, 0x3e, 0x48, 0xde, 0x83, 0x6b, 0xf4, 0x9a, 0x82, 0x6d, 0x21, 0xec, 0xf3,
	0xed, 0xaf, 0x46, 0xfb, 0xbf, 0x9c, 0xeb, 0x35, 0xdb, 0x1e, 0xae, 0x06, 0xac, 0xc1, 0xc8, 0x07,
	0x70, 0x8b, 0x4b, 0x43, 0x7d, 0x4b, 0xbf, 0x3a, 0x48, 0x7f, 0x5d, 0x65, 0xd8, 0xc7, 0x8b, 0x4b,
	0x13, 0x03, 0x78, 0x9d, 0x60, 0xf4, 0xd7, 0x01, 0xd8, 0x37, 0x49, 0xbe, 0x01, 0x54, 0x5a, 0x95,
	0x58, 0xdf, 0xe2, 0xca, 0xd8, 0x61, 0xf9, 0x93, 0x8b, 0xff, 0x79, 0x5e, 0xc4, 0xb0, 0xd6, 0x9b,
	0xab, 0x01, 0xeb, 0xf1, 0xe7, 0x53, 0x38, 0xb6, 0x69, 0xf2, 0x1c, 0x7c, 0xdd, 0x04, 0x09, 0x57,
	0x2b, 0x59, 0x5b, 0xdf, 0x53, 0x06, 0x36, 0x35, 0x6d, 0x32, 0xe4, 0x29, 0x78, 0x4a, 0x26, 0x5c,
	0xe5, 0x68, 0xe8, 0x30, 0x70, 0xc3, 0x53, 0x76, 0xa2, 0xe4, 0xb4, 0x39, 0xc6, 0x0f, 0xfa, 0x0d,
	0x8e, 0x7e, 0x81, 0xd7, 0x8d, 0x85, 0xbc, 0x81, 0x33, 0x21, 0xed, 0x68, 0x30, 0x31, 0x85, 0xa8,
	0x92, 0x35, 0x6a, 0xb1, 0xd8, 0x58, 0x7b, 0x8f, 0x91, 0xae, 0x36, 0x2f, 0x44, 0xf5, 0xd3, 0x56,
	0x9a, 0x3e, 0xda, 0x77, 0x24, 0x76, 0x19, 0x87, 0x76, 0x19, 0xa1, 0x4d, 0xcd, 0xd2, 0x12, 0x2f,
	0x9e, 0x81, 0xd7, 0x2d, 0x1a, 0x79, 0x04, 0x3e, 0xbb, 0xfe, 0x31, 0xfb, 0x94, 0xb0, 0xeb, 0xf8,
	0xcb, 0xec, 0xf1, 0x20, 0xbb, 0x67, 0xd7, 0xfa, 0xdd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5,
	0xd2, 0x03, 0x8e, 0x47, 0x03, 0x00, 0x00,
}
