// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kedge/config/http/backends/backend.proto

/*
Package kedge_config_http_backends is a generated protocol buffer package.

It is generated from these files:
	kedge/config/http/backends/backend.proto

It has these top-level messages:
	Backend
	Middleware
	Security
*/
package kedge_config_http_backends

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"
import  kedge_config_common_resolvers "github.com/improbable-eng/kedge/protogen/kedge/config/common/resolvers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// / Balancer chooses which HTTP backend balancing policy to use.
type Balancer int32

const (
	// ROUND_ROBIN is the simpliest and default load balancing policy
	Balancer_ROUND_ROBIN Balancer = 0
)

var Balancer_name = map[int32]string{
	0: "ROUND_ROBIN",
}
var Balancer_value = map[string]int32{
	"ROUND_ROBIN": 0,
}

func (x Balancer) String() string {
	return proto.EnumName(Balancer_name, int32(x))
}
func (Balancer) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// / Backend data will be used to set up pool of HTTP connection to specified endpoint that will be kept open.
type Backend struct {
	// / name is the string identifying the backend in all other configs.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// / balancer decides which balancing policy to use.
	Balancer Balancer `protobuf:"varint,2,opt,name=balancer,enum=kedge.config.http.backends.Balancer" json:"balancer,omitempty"`
	// / disable_conntracking turns off the /debug/events tracing and Prometheus monitoring of the pool sie for this backend.
	DisableConntracking bool `protobuf:"varint,3,opt,name=disable_conntracking,json=disableConntracking" json:"disable_conntracking,omitempty"`
	// / security controls the TLS connection details for the backend (HTTPS). If not present, insecure HTTP mode is used.
	Security *Security `protobuf:"bytes,4,opt,name=security" json:"security,omitempty"`
	// Types that are valid to be assigned to Resolver:
	//	*Backend_Srv
	//	*Backend_K8S
	//	*Backend_Host
	Resolver      isBackend_Resolver `protobuf_oneof:"resolver"`
	Autogenerated bool               `protobuf:"varint,6,opt,name=autogenerated" json:"autogenerated,omitempty"`
}

func (m *Backend) Reset()                    { *m = Backend{} }
func (m *Backend) String() string            { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()               {}
func (*Backend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isBackend_Resolver interface {
	isBackend_Resolver()
}

type Backend_Srv struct {
	Srv *kedge_config_common_resolvers.SrvResolver `protobuf:"bytes,10,opt,name=srv,oneof"`
}
type Backend_K8S struct {
	K8S *kedge_config_common_resolvers.K8SResolver `protobuf:"bytes,11,opt,name=k8s,oneof"`
}
type Backend_Host struct {
	Host *kedge_config_common_resolvers.HostResolver `protobuf:"bytes,12,opt,name=host,oneof"`
}

func (*Backend_Srv) isBackend_Resolver()  {}
func (*Backend_K8S) isBackend_Resolver()  {}
func (*Backend_Host) isBackend_Resolver() {}

func (m *Backend) GetResolver() isBackend_Resolver {
	if m != nil {
		return m.Resolver
	}
	return nil
}

func (m *Backend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Backend) GetBalancer() Balancer {
	if m != nil {
		return m.Balancer
	}
	return Balancer_ROUND_ROBIN
}

func (m *Backend) GetDisableConntracking() bool {
	if m != nil {
		return m.DisableConntracking
	}
	return false
}

func (m *Backend) GetSecurity() *Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *Backend) GetSrv() *kedge_config_common_resolvers.SrvResolver {
	if x, ok := m.GetResolver().(*Backend_Srv); ok {
		return x.Srv
	}
	return nil
}

func (m *Backend) GetK8S() *kedge_config_common_resolvers.K8SResolver {
	if x, ok := m.GetResolver().(*Backend_K8S); ok {
		return x.K8S
	}
	return nil
}

func (m *Backend) GetHost() *kedge_config_common_resolvers.HostResolver {
	if x, ok := m.GetResolver().(*Backend_Host); ok {
		return x.Host
	}
	return nil
}

func (m *Backend) GetAutogenerated() bool {
	if m != nil {
		return m.Autogenerated
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Backend) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Backend_OneofMarshaler, _Backend_OneofUnmarshaler, _Backend_OneofSizer, []interface{}{
		(*Backend_Srv)(nil),
		(*Backend_K8S)(nil),
		(*Backend_Host)(nil),
	}
}

func _Backend_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Backend)
	// resolver
	switch x := m.Resolver.(type) {
	case *Backend_Srv:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Srv); err != nil {
			return err
		}
	case *Backend_K8S:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.K8S); err != nil {
			return err
		}
	case *Backend_Host:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Host); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Backend.Resolver has unexpected type %T", x)
	}
	return nil
}

func _Backend_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Backend)
	switch tag {
	case 10: // resolver.srv
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kedge_config_common_resolvers.SrvResolver)
		err := b.DecodeMessage(msg)
		m.Resolver = &Backend_Srv{msg}
		return true, err
	case 11: // resolver.k8s
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kedge_config_common_resolvers.K8SResolver)
		err := b.DecodeMessage(msg)
		m.Resolver = &Backend_K8S{msg}
		return true, err
	case 12: // resolver.host
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kedge_config_common_resolvers.HostResolver)
		err := b.DecodeMessage(msg)
		m.Resolver = &Backend_Host{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Backend_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Backend)
	// resolver
	switch x := m.Resolver.(type) {
	case *Backend_Srv:
		s := proto.Size(x.Srv)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Backend_K8S:
		s := proto.Size(x.K8S)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Backend_Host:
		s := proto.Size(x.Host)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// TODO(bplotka): Implemment that. Not really supported now.
type Middleware struct {
	// Types that are valid to be assigned to Middleware:
	//	*Middleware_Retry_
	Middleware isMiddleware_Middleware `protobuf_oneof:"Middleware"`
}

func (m *Middleware) Reset()                    { *m = Middleware{} }
func (m *Middleware) String() string            { return proto.CompactTextString(m) }
func (*Middleware) ProtoMessage()               {}
func (*Middleware) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isMiddleware_Middleware interface {
	isMiddleware_Middleware()
}

type Middleware_Retry_ struct {
	Retry *Middleware_Retry `protobuf:"bytes,1,opt,name=retry,oneof"`
}

func (*Middleware_Retry_) isMiddleware_Middleware() {}

func (m *Middleware) GetMiddleware() isMiddleware_Middleware {
	if m != nil {
		return m.Middleware
	}
	return nil
}

func (m *Middleware) GetRetry() *Middleware_Retry {
	if x, ok := m.GetMiddleware().(*Middleware_Retry_); ok {
		return x.Retry
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Middleware) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Middleware_OneofMarshaler, _Middleware_OneofUnmarshaler, _Middleware_OneofSizer, []interface{}{
		(*Middleware_Retry_)(nil),
	}
}

func _Middleware_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Middleware)
	// Middleware
	switch x := m.Middleware.(type) {
	case *Middleware_Retry_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Retry); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Middleware.Middleware has unexpected type %T", x)
	}
	return nil
}

func _Middleware_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Middleware)
	switch tag {
	case 1: // Middleware.retry
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Middleware_Retry)
		err := b.DecodeMessage(msg)
		m.Middleware = &Middleware_Retry_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Middleware_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Middleware)
	// Middleware
	switch x := m.Middleware.(type) {
	case *Middleware_Retry_:
		s := proto.Size(x.Retry)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Middleware_Retry struct {
	// / retry_count specifies how many times to retry.
	RetryCount uint32 `protobuf:"varint,1,opt,name=retry_count,json=retryCount" json:"retry_count,omitempty"`
	// / on_codes specifies the list of codes to retry on.
	OnCodes []uint32 `protobuf:"varint,2,rep,packed,name=on_codes,json=onCodes" json:"on_codes,omitempty"`
}

func (m *Middleware_Retry) Reset()                    { *m = Middleware_Retry{} }
func (m *Middleware_Retry) String() string            { return proto.CompactTextString(m) }
func (*Middleware_Retry) ProtoMessage()               {}
func (*Middleware_Retry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Middleware_Retry) GetRetryCount() uint32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func (m *Middleware_Retry) GetOnCodes() []uint32 {
	if m != nil {
		return m.OnCodes
	}
	return nil
}

// / Security settings for a backend.
type Security struct {
	// / insecure_skip_verify skips the server certificate verification completely.
	// / No TLS config (for testclient or server) will be used. This should *not* be used in production software.
	InsecureSkipVerify bool `protobuf:"varint,1,opt,name=insecure_skip_verify,json=insecureSkipVerify" json:"insecure_skip_verify,omitempty"`
	// / config_name indicates the TlsServerConfig to be used for this connection.
	ConfigName string `protobuf:"bytes,2,opt,name=config_name,json=configName" json:"config_name,omitempty"`
}

func (m *Security) Reset()                    { *m = Security{} }
func (m *Security) String() string            { return proto.CompactTextString(m) }
func (*Security) ProtoMessage()               {}
func (*Security) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Security) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func (m *Security) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func init() {
	proto.RegisterType((*Backend)(nil), "kedge.config.http.backends.Backend")
	proto.RegisterType((*Middleware)(nil), "kedge.config.http.backends.Middleware")
	proto.RegisterType((*Middleware_Retry)(nil), "kedge.config.http.backends.Middleware.Retry")
	proto.RegisterType((*Security)(nil), "kedge.config.http.backends.Security")
	proto.RegisterEnum("kedge.config.http.backends.Balancer", Balancer_name, Balancer_value)
}

func init() { proto.RegisterFile("kedge/config/http/backends/backend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x97, 0x75, 0x7f, 0xb2, 0xb7, 0x1b, 0x20, 0xb3, 0x43, 0x28, 0x87, 0x55, 0x55, 0x0f,
	0xd1, 0x68, 0x93, 0x51, 0xd0, 0x54, 0x2e, 0x08, 0xd2, 0x1d, 0x8a, 0x10, 0x9d, 0xe4, 0x0a, 0x2e,
	0x68, 0x44, 0x6e, 0xe2, 0xa5, 0x56, 0x1a, 0xbb, 0xb2, 0xdd, 0x56, 0x03, 0xf1, 0x71, 0xf8, 0x5c,
	0x48, 0xf0, 0x45, 0x50, 0x9c, 0xa6, 0x7f, 0x0e, 0x0c, 0x6e, 0xce, 0xf3, 0x3e, 0xbf, 0xe7, 0xb5,
	0x5f, 0x3b, 0xe0, 0xa6, 0x34, 0x4e, 0xa8, 0x1f, 0x09, 0x7e, 0xcb, 0x12, 0x7f, 0xac, 0xf5, 0xd4,
	0x1f, 0x91, 0x28, 0xa5, 0x3c, 0x56, 0xe5, 0xc2, 0x9b, 0x4a, 0xa1, 0x05, 0xaa, 0x19, 0xa7, 0x57,
	0x38, 0xbd, 0xdc, 0xe9, 0x95, 0xce, 0xda, 0x65, 0xc2, 0xf4, 0x78, 0x36, 0xf2, 0x22, 0x91, 0xf9,
	0xd9, 0x82, 0xe9, 0x54, 0x2c, 0xfc, 0x44, 0xb4, 0x0d, 0xd8, 0x9e, 0x93, 0x09, 0x8b, 0x89, 0x16,
	0x52, 0xf9, 0xab, 0x65, 0x91, 0x59, 0x6b, 0x6f, 0x75, 0x8f, 0x44, 0x96, 0x09, 0xee, 0x4b, 0xaa,
	0xc4, 0x64, 0x4e, 0xa5, 0x5a, 0xaf, 0x0a, 0x7b, 0xe3, 0x77, 0x05, 0x0e, 0x83, 0xa2, 0x27, 0x6a,
	0xc1, 0x1e, 0x27, 0x19, 0x75, 0xac, 0xba, 0xe5, 0x1e, 0x05, 0xce, 0xaf, 0x9f, 0x67, 0xa7, 0x80,
	0xbe, 0x7c, 0x26, 0xed, 0xaf, 0xe1, 0x45, 0xfb, 0x95, 0x77, 0xf3, 0xad, 0xd3, 0xba, 0x7c, 0xf9,
	0xbd, 0x89, 0x8d, 0x0b, 0xbd, 0x01, 0x7b, 0x44, 0x26, 0x84, 0x47, 0x54, 0x3a, 0xbb, 0x75, 0xcb,
	0x7d, 0xd0, 0x69, 0x7a, 0x7f, 0x3f, 0x8f, 0x17, 0x2c, 0xbd, 0x78, 0x45, 0xa1, 0xe7, 0x70, 0x1a,
	0x33, 0x45, 0x46, 0x13, 0x1a, 0x46, 0x82, 0x73, 0x2d, 0x49, 0x94, 0x32, 0x9e, 0x38, 0x95, 0xba,
	0xe5, 0xda, 0xf8, 0xf1, 0xb2, 0xd6, 0xdb, 0x28, 0xe5, 0x4d, 0x15, 0x8d, 0x66, 0x92, 0xe9, 0x3b,
	0x67, 0xaf, 0x6e, 0xb9, 0xd5, 0xfb, 0x9b, 0x0e, 0x97, 0x5e, 0xbc, 0xa2, 0xd0, 0x6b, 0xa8, 0x28,
	0x39, 0x77, 0xc0, 0xc0, 0xe7, 0xdb, 0x70, 0x31, 0x2d, 0x6f, 0x3d, 0xa3, 0xa1, 0x9c, 0xe3, 0xe5,
	0x47, 0x7f, 0x07, 0xe7, 0x60, 0xce, 0xa7, 0x5d, 0xe5, 0x54, 0xff, 0x8b, 0x7f, 0xdf, 0x55, 0x9b,
	0x7c, 0xda, 0x55, 0xe8, 0x2d, 0xec, 0x8d, 0x85, 0xd2, 0xce, 0xb1, 0x09, 0x78, 0xf6, 0x8f, 0x80,
	0xbe, 0x50, 0x7a, 0x23, 0xc1, 0xa0, 0xa8, 0x09, 0x27, 0x64, 0xa6, 0x45, 0x42, 0x39, 0x95, 0x44,
	0xd3, 0xd8, 0x39, 0x30, 0x03, 0xdb, 0x16, 0x03, 0x00, 0xbb, 0xcc, 0x69, 0xfc, 0xb0, 0x00, 0x3e,
	0xb0, 0x38, 0x9e, 0xd0, 0x05, 0x91, 0x14, 0x5d, 0xc1, 0xbe, 0xa4, 0x5a, 0xde, 0x99, 0x9b, 0xae,
	0x76, 0x5a, 0xf7, 0x8d, 0x70, 0x8d, 0x79, 0x38, 0x67, 0xfa, 0x3b, 0xb8, 0x80, 0x6b, 0x3d, 0xd8,
	0x37, 0x0a, 0x3a, 0x83, 0xaa, 0x51, 0xc2, 0x48, 0xcc, 0xb8, 0x36, 0xa1, 0x27, 0x18, 0x8c, 0xd4,
	0xcb, 0x15, 0xf4, 0x04, 0x6c, 0xc1, 0xc3, 0x48, 0xc4, 0x54, 0x39, 0xbb, 0xf5, 0x8a, 0x7b, 0x82,
	0x0f, 0x05, 0xef, 0xe5, 0x9f, 0xc1, 0xf1, 0xe6, 0xc6, 0x1a, 0x37, 0x60, 0x97, 0x57, 0x86, 0x2e,
	0xe0, 0x94, 0x71, 0x73, 0x6d, 0x34, 0x54, 0x29, 0x9b, 0x86, 0x73, 0x2a, 0xd9, 0x6d, 0xb1, 0x67,
	0x1b, 0xa3, 0xb2, 0x36, 0x4c, 0xd9, 0xf4, 0x93, 0xa9, 0xe4, 0xfb, 0x28, 0x8e, 0x10, 0x9a, 0x67,
	0x9c, 0x3f, 0xca, 0x23, 0x0c, 0x85, 0x34, 0x20, 0x19, 0x3d, 0x7f, 0x0a, 0x76, 0xf9, 0x0c, 0xd1,
	0x43, 0xa8, 0xe2, 0xeb, 0x8f, 0x83, 0xab, 0x10, 0x5f, 0x07, 0xef, 0x06, 0x8f, 0x76, 0x46, 0x07,
	0xe6, 0x87, 0x78, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x71, 0x49, 0x93, 0x3c, 0xbf, 0x03, 0x00,
	0x00,
}
